bkd-mba-fbi/evento-portal

.github/workflows/build.yml
.github/workflows/test.yml
README.md
package.json

Die Workflows zum ausführen von Linting & (Cypress-)Tests und zum Builden/Deployen des ZIPs funktionieren soweit. Ich konnte es allerdings nur im geforkten Repo testen, da mir die Berechtigungen fehlen. Die Badges sollten dann auch erscheinen.
Allenfalls muss dann noch in den Repo Settings unter «Actions», «General», «Workflow permissions» auf «Read and write permissions» gesetzt werden, damit das ZIP Deployment klappt.

Deployment: GitHub Action Worflows

---

README.md
package-lock.json
package.json
src/components/Content.ts
src/components/Portal.ts
src/settings.ts
src/utils/auth.ts
src/utils/storage.ts
src/utils/token.ts

Noch offen:
Im Moment hat es auch noch auskommentierten Code, der aber je nach dem zu Einsatz käme wenn eine asynchrones Refreshing möglich wird. Ausserdem sind zum Debuggen auch noch ein paar `console.log` Statements drin.
Um alles zu resetten (d.h. erneut einloggen) kann folgendes gemacht werden:
```
sessionStorage.clear();
localStorage.clear();
```

Login #540

---

.gitignore
README.md
cypress/support/commands.ts
cypress/tsconfig.json
index.html
public/settings.example.js
src/settings.ts
src/typings.d.ts
src/utils/auth.ts
src/utils/fetch.ts
tsconfig.json

Ich habe mal einen Wurf gemacht mit separatem `public/settings.js`...

Add public/settings.js for environment-specific settings

---

cypress/e2e/navigationMenu.cy.ts
src/settings.ts

Siehe https://github.com/bkd-mba-fbi/webapp-schulverwaltung/issues/525#issuecomment-1631928478

Change order of main navigation #536

---

public/apps/EmberApps/Fotoliste/index.html
public/apps/Noteneingabe/index.html
public/scripts/iframe.js
tsconfig.json

- Fehlendes iframe.js bei Fotoliste & Noteneingabe hinzugefügt
- MutationObserver für absolut positionierte Elemente implementiert.

Resize iframe observing the absolute positioned elements #556

---

.github/workflows/deployTestEnv.yml

Damit @fbufbi die neusten fix und features direkt auf https://evtapp.netlify.app/ zur Verfügung hat, ohne ein merge von main nach test.

deploy Test Env also on main branch

---

src/components/Portal.ts
src/state/portal-state.ts
src/utils/navigation.ts

Update navigation item based on actual app path #575

---

src/components/Header.ts
src/components/Header/NavItemLink.ts
src/components/Portal.ts
src/state/portal-state.ts

Fix für 
- https://github.com/bkd-mba-fbi/webapp-schulverwaltung/issues/577
- https://github.com/bkd-mba-fbi/webapp-schulverwaltung/issues/575#issuecomment-1640009385
- https://github.com/bkd-mba-fbi/webapp-schulverwaltung/issues/546#issuecomment-1663558448

Fix home button navigation and redirect to home #575 # 577

---

.github/workflows/container-build.yml
build/evento.conf

Add semver to release Tags for Backagesync

---

src/components/Footer.ts

Siehe https://github.com/bkd-mba-fbi/webapp-schulverwaltung/issues/618
Zusammen mit https://github.com/bkd-mba-fbi/webapp-schulverwaltung/pull/630 mergen.

Layout adjustments

---

cypress/tsconfig.json
package-lock.json
package.json
src/components/Header/NotificationsToggle.ts
src/env-settings.ts
src/utils/auth.ts
src/utils/token-renewal.ts
tsconfig.json

Siehe #159 
Habe im Zuge dessen auch gleich noch einmal die Dependencies updated (gab eine Vulnerability mit Severity "High").

Logout redirect to home

---

public/apps/EmberApps/PersonPhoto/main.css

Auf kleinen Laptop screens kann die Photapp nicht geschlossen werden. Scroll wird ermöglicht.

Enable scroll on modal

---

.github/workflows/bom.yml
.github/workflows/container-build.yml
.github/workflows/deployTestEnv.yml
.github/workflows/hotfix-container-build.yml
.github/workflows/test.yml
.github/workflows/zip.yml

Analog zu https://github.com/bkd-mba-fbi/webapp-schulverwaltung/pull/682

Set Node.js version via env instead of matrix & update actions

---

src/state/portal-state.ts

Siehe Kommentar https://github.com/bkd-mba-fbi/evento-portal/issues/166#issuecomment-2089709917

Prevent undefined locale before user is authenticated #166

---

src/utils/fetch.ts

Siehe https://github.com/bkd-mba-fbi/evento-portal/issues/178

Change CLX-Authorization header to Authorization #178

---

package-lock.json
src/state/portal-state.ts

Avoid navigation after token renewal #213

---

cypress/e2e/navigationMenu.cy.ts
public/locales/fr-CH.js
src/settings.ts
xliff/fr-CH.xlf

Merge after https://github.com/bkd-mba-fbi/webapp-schulverwaltung/pull/796

Replace old eventRegistration with new import #758

---

README.md
doc/hotfix-webapp-schulverwaltung.md
doc/releasing.md

Siehe #223
@schefbi Ich habe die Dokumentation ergänzt und bin froh um ein Review → https://github.com/bkd-mba-fbi/evento-portal/blob/doc/223-webapp-hotfix/doc/hotfix-webapp-schulverwaltung.md

Add documentation for webapp hotfix #223

---

public/styles/kursausschreibung-override.css

Subnav Background from grey to red + border radius

gem:30459 Evento-Portal Kursausschreibung Eventcode filter css

---

public/scripts/iframe.js

https://github.com/bkd-mba-fbi/webapp-schulverwaltung/issues/813

Fix calculation of max positioned bottom in iframe.js #813
